apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--web
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}--web
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5173
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: "http://{{ .Release.Name }}--api.{{ .Values.namespace }}.svc.cluster.local:3000/api"